# Generated by Django 4.1.7 on 2023-03-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Performer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "performer",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vol", models.CharField(max_length=16)),
                ("old_vol", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("performer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bmonster.performer")),
            ],
            options={
                "db_table": "program",
            },
        ),
        migrations.CreateModel(
            name="FavoriteProgram",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("star", models.IntegerField()),
                ("comment", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bmonster.program")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "favorite_program",
            },
        ),
        migrations.CreateModel(
            name="FavoritePerformer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("star", models.IntegerField()),
                ("comment", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("performer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bmonster.performer")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "favorite_performer",
            },
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(fields=("performer", "vol"), name="program_u_idx_1"),
        ),
        migrations.AddConstraint(
            model_name="favoriteprogram",
            constraint=models.UniqueConstraint(fields=("user", "program"), name="favorite_program_u_idx_1"),
        ),
        migrations.AddConstraint(
            model_name="favoriteperformer",
            constraint=models.UniqueConstraint(fields=("user", "performer"), name="favorite_performer_u_idx_1"),
        ),
    ]
