# Generated by Django 4.1.7 on 2023-03-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmonster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_program',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteprogram',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='favorite_program_u_idx_1'),
        ),
    ]
