# Generated by Django 4.1.7 on 2023-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmonster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePerformer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.performer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_performer',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteperformer',
            constraint=models.UniqueConstraint(fields=('user', 'performer'), name='favorite_performer_u_idx_1'),
        ),
    ]
